/**
 * The `.js` files under src/ forward to the `.ts` sources; dist/ is a self-contained,
 * type-free copy of the library. Both are generated by scripts/build-js.mjs.
 */
import assert from "node:assert/strict";
import { describe, it } from "node:test";

import * as ts from "../src/index.ts";
// @ts-expect-error - generated build, no type declarations of its own.
import * as srcJs from "../src/index.js";
// @ts-expect-error - generated build, no type declarations of its own.
import * as dist from "../dist/index.js";

describe("generated builds", () => {
  it("resolves .js specifiers to the same modules as .ts", () => {
    assert.equal(srcJs.GBNF, ts.GBNF);
    assert.equal(srcJs.RuleChar, ts.RuleChar);
  });

  it("exports the same names from dist as from the sources", () => {
    assert.deepEqual(Object.keys(dist).sort(), Object.keys(ts).sort());
  });

  it("parses grammars identically in the dist build", () => {
    const grammar = 'root ::= "foo" | [a-z]+';
    const fromDist = [...dist.GBNF(grammar).add("f")].map((rule: unknown) =>
      JSON.stringify(rule),
    );
    const fromTs = [...ts.GBNF(grammar).add("f")].map((rule) => JSON.stringify(rule));
    assert.deepEqual(fromDist.sort(), fromTs.sort());
  });

  it("throws the same errors in the dist build", () => {
    assert.throws(() => dist.GBNF("root ::= foo"), {
      message: /Undefined rule identifier/,
    });
  });
});
