[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gbnf"
version = "0.0.30"
description = "A library for parsing GBNF grammars"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Ambient Labs", email = "maintainers@gbnf.dev" }]
requires-python = ">=3.8"
dependencies = []

[project.urls]
homepage = "https://github.com/ambient-labs/GBNF/packages/gbnf"

[tool.setuptools.packages.find]
include = ["gbnf*"]
